### PR TITLE
Validate Submission Licenses

### LINKED ISSUE #236: LICENSE detection not working for jojoe77777/Slapper
I'm attempting to submit Slapper 1.6.0, and the auto-detect LICENSE button doesn't pick up the common LGPL-3.0 license from the repo which has been there for the last 4 years.
https://github.com/jojoe77777/Slapper/blob/324b48dea27ed636f6a84f5afa7090cb2568eba0/LICENSE

### PR DESCRIPTION
**Pull request by jasonw4331**
This PR completes some TODO list items which have existed since the beginning:
1. License name validation
2. Creation of a license when none is uploaded

### CODE REVIEW

**Comment by JaxkDev** [comment]
Does this change the dropdown list options too or just detection from gh?

**Comment by jasonw4331** [comment]
No, this only writes in missing license files and validates the dropdown output against the existing file

**Comment by JaxkDev** [comment]
Looks good, just need to update the dropdown/detection first before it can ever reach the server side checks.

See https://github.com/poggit/poggit/blob/5e872ec0811f914c44888fd14d48d23f67043728/js/newSubmit.js#L736 for the dropdown

**Comment by JaxkDev** [comment]
see #325

**Pull request closed without merging**
