### PR TITLE
Auto-Update docker image

### PR DESCRIPTION
**Pull request by JaxkDev**
Pull the latest image if a update is found.
- Allows poggit to run the latest PMMP API (around 2-10min after pmmp is updated on docker)
- Fully automated (Using docker hubs auto-build)

(Untested, this should in theory update when pmmp does)
image

### CODE REVIEW

**Comment by SOF3** [comment]
Does it return 0 no matter it updated or not?

**Comment by JaxkDev** [comment]
> Does it return 0 no matter it updated or not?

Yes, you could check the stdout for key words to differentiate the cases but output could vary in docker versions etc

**Comment by SOF3** [comment]
I'm wondering if we could use APCU to run pull at most once per hour.

**Comment by JaxkDev** [comment]
Yeah can do, will update tomorrow.

**Comment by JaxkDev** [comment]
Or there’s the option of using their webhooks to tell poggit when the image is updated, what’d you fancy

**Comment by SOF3** [comment]
I guess the webhook approach is better.

**Pull request closed without merging**
