### PR TITLE
PHP8

### PR DESCRIPTION
**Pull request by JaxkDev**
This PR requires server to update to PHP8 before pulling this PR as it will break dev builds due to token changes if ran on PHP7.

### CODE REVIEW

**Comment by jasonw4331** [comment]
Since pocketmine's base php requirement is now php8, can this be pushed forward a bit? or is this already running on beta?

**Comment by JaxkDev** [comment]
> Since pocketmine's base php requirement is now php8, can this be pushed forward a bit? or is this already running on beta?

Can’t merge PR because @SOF3 cant update the docker image to PHP8 for some reason 🤷‍♂️

**Comment by SOF3** [comment]
Any thoughts about running PHP lint in a container instead of the binaries used to run Poggit? That should have better compatibility in the long term anyway.

The problem right now is that I can't build the Poggit image on PHP 8.0 due to some PECL problems, and it's a deep hole to dig into.

**Comment by JaxkDev** [comment]
Ideally everything to be containerised including build but I have no where near the time required for that haven’t even had time to fix/rewrite phpstan yet or PM4 support.

**Comment by SOF3** [comment]
Running lint on a single PHP file should be easier though. Probably doesn't even require maintaining our own image.

**Comment by JaxkDev** [comment]
Hold this PR, found an issue with PSR-0 Lint displaying some odd location

Screenshot 2021-11-30 at 17 47 28
vs 


Screenshot 2021-11-30 at 17 47 53

**Review by SOF3 — APPROVED** [review]

**Pull request merged**
