### PR TITLE
Adding average score to JSON API

### PR DESCRIPTION
**Pull request by jasonw4331**
I'm making a mobile app and noticed this information was missing from the API. I have yet to test it, but from what I've seen so far it should work.

### CODE REVIEW

**Review by SOF3 — APPROVED** [review]

**Comment by JaxkDev** [comment]
@jasonwynn10 PR's ok however it's rounding to 1 DP in the sql call but then cast to int ?
Should it be left rounded to a int or a float score ?

**Review by JaxkDev — APPROVED** [review]
Tested.

**Comment by jasonw4331** [comment]
It's been so long since I've looked at this PR I cant remember if that was intentional or not lol

**Comment by JaxkDev** [comment]
Just choose something and I'll merge tomorrow

**Pull request merged**
