### PR TITLE
Added basic virion building

### PR DESCRIPTION
**Pull request by SOF3**
Obsoletes #57

### CODE REVIEW

**Comment by Awzaw** [comment]
Worked for me, good to merge

**Comment by SOF3** [comment]
@Awzaw just the normal builds working, or virion builds working? Ever tested installing virions on local plugins?

**Comment by Awzaw** [comment]
I tried to understand how it all works... trying again now

**Comment by Awzaw** [comment]
I can't get [PoolExample](https://github.com/Awzaw/PoolExample/) to compile with libasynql (as external at libasynql, poggit/libasynql or poggit/libasynql/libasynql) on new-virion: I'm basing my poggit.yml on this - is it still correct, and which libs config should I be testing?

```
branches: master
projects:
  First:
    path: FirstPlugin
    libs:
      - local: libuncommon <span class="code"># name of a project in this repo</span>
      - external: librarian/libstrange/libstrange <span class="code"># full path of a project from another repo on Poggit</span>
      - raw-virion: libs/libodd.phar <span class="code"># this repo has a file libs/libodd.phar</span>
      - raw-virion: http://libextraordinary.com/raw.phar
  another:
    path: AnotherPlugin
    model: virion
  libuncommon:
    path: UncommonLib
    type: library
    model: virion
```

**Comment by SOF3** [comment]
@Awzaw actually, compiling projects with virions has not been added to Poggit yet. This pull request only adds the initial virion building.

I also figured that it's probably easier to have the library syntax in command form:

```yaml
libs:
  - project local libuncommon
  - project external librarin/libstrange/libstrange
  - raw local libs/libodd.phar
  - raw online http://libextraordinary.com/raw.phar

**Pull request merged**
