### PR TITLE
Voting

### PR DESCRIPTION
**Pull request by Awzaw**
Voting for logged in users on other authors' plugins, promotion/demotion between Checked <-> Voted only

### CODE REVIEW

**Comment by SOF3** [comment]
So no rejection vote?

**Comment by Awzaw** [comment]
Couldn't think of an elegant solution for that with a single button :-/ I'll try again

**Comment by SOF3** [comment]
Why not call it "Approve"/"Reject" directly? Then show a message "%d people approved, %d people rejected. The plugin will be approved when %d more people approve, or rejected when %d more people reject".

Only showing it for Checked plugins.

**Comment by Awzaw** [comment]
what if you've approved, then change your mind? Need approve, unapprove, reject, unreject....

**Comment by Awzaw** [comment]
Added nice pretty icons, I think that's worth a merge :-)

**Pull request merged**
